@DotNet8.Architectures.ModularMonolithic.Modules.Presentation_HostAddress = http://localhost:5274

GET {{DotNet8.Architectures.ModularMonolithic.Modules.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
